version: '3'

services:
  backend:
    build: ../ads-serve
    ports:
      - "4001:4000"
    depends_on:
      - postgres-ads
      - challenge
    links:
      - postgres-ads
      - challenge
    environment:
      - AD_DB_URI=postgres://postgres:postgres@postgres-ads:5432/ads
      - AD_CHALLENGE_BYPASS_SERVER=http://challenge:2416/v1
  postgres-ads:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=ads
    volumes:
     - "../dbdata/ad:/var/lib/postgresql/data"
  postgres-challenge:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=challenge
    volumes:
     - "../dbdata/challenge:/var/lib/postgresql/data"
  frontend:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - backend
    links:
      - backend
    environment:
      - REACT_APP_SERVER_ADDRESS=http://localhost:4001/v1
  challenge:
      build: ../challenge-bypass-server
      depends_on:
        - postgres-challenge
      links:
        - postgres-challenge
      environment:
        - DATABASE_URL=postgres://postgres:postgres@postgres-challenge:5432/challenge?sslmode=disable


